### ISSUE TITLE
Request/Suggestion

### ISSUE THREAD

**Issue by idkjs** [chaselambda/makefiletutorial#10]
Can you include an example of how to use of `MAKEFILE_LIST`?

From the book in your link:

>3.5 The Variable MAKEFILE_LIST
As make reads various makefiles, including any obtained from the MAKEFILES variable, the com- mand line, the default files, or from include directives, their names will be automatically appended to the MAKEFILE_LIST variable. They are added right before make begins to parse them.
This means that if the first thing a makefile does is examine the last word in this variable, it will be the name of the current makefile. Once the current makefile has used include, however, the last word will be the just-included makefile.
If a makefile named Makefile has this content: 

```
name1 := $(lastword $(MAKEFILE_LIST))
    include inc.mk
name2 := $(lastword $(MAKEFILE_LIST)) all:
    @echo name1 = $(name1) 
    @echo name2 = $(name2)
```
>then you would expect to see this output:
name1 = Makefile name2 = inc.mk

What would you have to have in `inc.mk` for this example to run?

Thanks for sharing.

**Comment by chaselambda** [comment]
It seems that it doesn't matter what's in `inc.mk` -- the point of the example is after including it you could find out what file that was just included.

I'd rather not add this to the tutorial because I see this used very infrequently. It could be a better fit for more advanced tutorials.

Thanks for the message!
