### ISSUE TITLE
Mention .PHONY in make clean section

### ISSUE THREAD

**Issue by jxu** [chaselambda/makefiletutorial#54]
.PHONY should be mentioned in the make clean section, as while it is mentioned much later on in the article, clean is where it's commonly seen. https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html 

make all section should also include it as well for completeness (should there be a file named `all` for some reason)

**Comment by chaselambda** [comment]
You're correct, but I don't want to add it to the tutorial because:
- In practice, many people don't use `.PHONY` because of how rare files called `all` or `clean` are
- It will clutter up every example with a detail that's minimally important

Nevertheless, I've now pointed this point out explicitly. See https://github.com/theicfire/makefiletutorial/commit/06e5b9d911ed09f712ef5b22d0f0987ee68ff55c

Thanks!
